---
- hosts: all
  tasks:
  # Install Oracle Java 7
  - include: tasks/install_java.yml

  # Install Datastax Cassandra 2.0
  - include: tasks/install_cassandra.yml

  # Start Cassandra
  # - include: tasks/start_cassandra.yml 
