---
# Install Oracle Java 7

- hosts: all
  sudo: yes
  tasks:
  - name: Install python-software-properties
    apt: pkg=python-software-properties state=latest install_recommends=yes

  - name: Add Java repository to sources
    apt_repository: repo='ppa:webupd8team/java'

  - name: Autoaccept license for Java
    shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

  - name: Update APT package cache
    apt: update_cache=yes

  - name: Install Oracle Java 7
    apt: pkg=oracle-java7-installer state=latest install_recommends=yes

  - name: Set Oracle Java 7 as Default
    apt: pkg=oracle-java7-set-default state=latest install_recommends=yes

  - name: Install JNA (Java Native Access)
    apt: pkg=libjna-java state=latest install_recommends=yes
